return {
  'catppuccin/nvim',
  name = 'catppuccin',
  priority = 1000,
  opts = {
    flavour = 'auto',
    background = {
      dark = 'mocha',
      light = 'latte',
    },
    no_bold = true,
    term_colors = true,
    integrations = {
      treesitter = true,
      mason = true,
      gitsigns = true,
      blink_cmp = true,
      native_lsp = {
        enabled = true,
        -- Italics for virtual text (the inline notes), underlines for the actual error squiggle.
        virtual_text = {
          errors      = { 'italic' },
          hints       = { 'italic' },
          warnings    = { 'italic' },
          information = { 'italic' },
        },
        underlines = {
          errors      = { 'underline' },
          hints       = { 'underline' },
          warnings    = { 'underline' },
          information = { 'underline' },
        },
        inlay_hints = { background = true },
      },
    },
    color_overrides = {
      mocha = {
        rosewater = '#f4e0e0',
        flamingo  = '#efcdd5',
        pink      = '#ecc4f0',
        mauve     = '#c7abdf',
        red       = '#ea8dc1',
        maroon    = '#e5a1bd',
        peach     = '#feb097',
        yellow    = '#ffdfb8',
        green     = '#93e5b6',
        teal      = '#92e1e4',
        sky       = '#90d9f7',
        sapphire  = '#83c3f6',
        blue      = '#9eaffd',
        lavender  = '#c4b9fc',
        text      = '#cfd5f4',
        subtext1  = '#bcc1de',
        subtext0  = '#a8acc8',
        overlay2  = '#9598b2',
        overlay1  = '#81839c',
        overlay0  = '#6e6f86',
        surface2  = '#5a5b70',
        surface1  = '#47475a',
        surface0  = '#323244',
        base      = '#1f1e2e',
        mantle    = '#191825',
        crust     = '#12111b',
      },
      latte = {
        rosewater = '#db898c',
        flamingo  = '#d97891',
        pink      = '#d97ce7',
        mauve     = '#7e6695',
        red       = '#cf0068',
        maroon    = '#e3427d',
        peach     = '#ff6050',
        yellow    = '#eb863a',
        green     = '#00a25a',
        teal      = '#2390a7',
        sky       = '#4a9ff1',
        sapphire  = '#379cc3',
        blue      = '#605af3',
        lavender  = '#927ef9',
        text      = '#4e4e69',
        subtext1  = '#5e5e77',
        subtext0  = '#6e6e85',
        overlay2  = '#7e7f93',
        overlay1  = '#8d8fa1',
        overlay0  = '#9da0b0',
        surface2  = '#adb0be',
        surface1  = '#bdc0cc',
        surface0  = '#cdd0da',
        base      = '#eff1f5',
        mantle    = '#e7e9ef',
        crust     = '#dde0e8',
      },
    },
  },
  config = function(_, opts)
    require('catppuccin').setup(opts)
    vim.cmd.colorscheme('catppuccin')
  end,
}
