# background           -> base
# foreground           -> text
# cursor-color         -> rosewater
# cursor-text          -> crust
# selection-background -> overlay2
# selection-foreground -> base
# palette 0            -> surface1  (black)
# palette 1            -> red       (red)
# palette 2            -> green     (green)
# palette 3            -> yellow    (yellow)
# palette 4            -> blue      (blue)
# palette 5            -> pink      (magenta)
# palette 6            -> teal      (cyan)
# palette 7            -> subtext1  (white)
# palette 8            -> surface2  (bright black)
# palette 9            -> red       (bright red)
# palette 10           -> green     (bright green)
# palette 11           -> yellow    (bright yellow)
# palette 12           -> blue      (bright blue)
# palette 13           -> pink      (bright magenta)
# palette 14           -> teal      (bright cyan)
# palette 15           -> subtext0  (bright white)

background           = #eff1f5
foreground           = #4e4e69
cursor-color         = #db898c
cursor-text          = #dde0e8
selection-background = #7e7f93
selection-foreground = #eff1f5

palette = 0=#bdc0cc
palette = 1=#cf0068
palette = 2=#00a25a
palette = 3=#eb863a
palette = 4=#605af3
palette = 5=#d97ce7
palette = 6=#2390a7
palette = 7=#5e5e77
palette = 8=#adb0be
palette = 9=#cf0068
palette = 10=#00a25a
palette = 11=#eb863a
palette = 12=#605af3
palette = 13=#d97ce7
palette = 14=#2390a7
palette = 15=#6e6e85
