# background           -> base
# foreground           -> text
# cursor-color         -> rosewater
# cursor-text          -> crust
# selection-background -> overlay2
# selection-foreground -> base
# palette 0            -> surface1  (black)
# palette 1            -> red       (red)
# palette 2            -> green     (green)
# palette 3            -> yellow    (yellow)
# palette 4            -> blue      (blue)
# palette 5            -> pink      (magenta)
# palette 6            -> teal      (cyan)
# palette 7            -> subtext0  (white)
# palette 8            -> surface2  (bright black)
# palette 9            -> red       (bright red)
# palette 10           -> green     (bright green)
# palette 11           -> yellow    (bright yellow)
# palette 12           -> blue      (bright blue)
# palette 13           -> pink      (bright magenta)
# palette 14           -> teal      (bright cyan)
# palette 15           -> subtext1  (bright white)

background           = #1f1e2e
foreground           = #cfd5f4
cursor-color         = #f4e0e0
cursor-text          = #12111b
selection-background = #9598b2
selection-foreground = #1f1e2e

palette = 0=#47475a
palette = 1=#ea8dc1
palette = 2=#93e5b6
palette = 3=#ffdfb8
palette = 4=#9eaffd
palette = 5=#ecc4f0
palette = 6=#92e1e4
palette = 7=#a8acc8
palette = 8=#5a5b70
palette = 9=#ea8dc1
palette = 10=#93e5b6
palette = 11=#ffdfb8
palette = 12=#9eaffd
palette = 13=#ecc4f0
palette = 14=#92e1e4
palette = 15=#bcc1de
